#!/bin/bash
expect() {
  actual="`./undname $1`"
  [[ "$actual" == "$2" ]] || { echo "$2 expected, but got $actual"; exit 1; }
}

expect '?x@@3HA' 'int x'
expect '?x@@3PEAHEA' 'int*x'
expect '?x@@3PEAPEAHEA' 'int**x'
expect '?x@@3PEAY02HEA' 'int(*x)[3]'
expect '?x@@3PEAY124HEA' 'int(*x)[3][5]'
expect '?x@@3PEAY1NKM@5HEA' 'int(*x)[3500][6]'
expect '?x@@YAXMH@Z' 'void x(float,int)'
expect '?x@@YAXMH@Z' 'void x(float,int)'
expect '?x@@3P6AHMNH@ZEA' 'int(*x)(float,double,int)'

expect '?x@ns@@3HA' 'int ns::x'

echo OK
